addons:
  apt:
    packages:
    - libpthread-stubs0-dev
    - libgl1-mesa-dev
    - libx11-dev
    - libxrandr-dev
    - libudev-dev
    - libfreetype6-dev
    - libopenal-dev
    - libflac-dev
    - libglew1.5-dev
    - libjpeg8-dev
    - libsndfile1-dev
    - libxcb-image0-dev
    - libjpeg-dev
    - libboost-all-dev
language: cpp
compiler: clang
services: xvfb
dist: bionic
before_script:
  # SFML
  - wget https://www.sfml-dev.org/files/SFML-2.5.1-sources.zip
  - unzip SFML-2.5.1-sources.zip
  - cd SFML-2.5.1
  - mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/usr .. ;
  - make install -j
  # Cmake
  - mkdir -p ${TRAVIS_BUILD_DIR}/build && cd ${TRAVIS_BUILD_DIR}/build
  - cmake -DCMAKE_INSTALL_PREFIX=${TRAVIS_BUILD_DIR}/usr -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-I${TRAVIS_BUILD_DIR}/usr/include" .. && cmake -LA ..
  - make -j VERBOSE=1
  - cd ..
script:
  - bash -c 'if ! ASAN_OPTIONS=detect_leaks=0 ./build/tests/ug-test "~[skip]"; then >&2 echo "Fail"; exit 1; fi'
  - bash -c 'if ! xvfb-run --server-args="-screen 0 1280x1024x24" -e /dev/stdout -a node tests/integration/smoke_tests.js; then >&2 echo "Fail"; exit 1; fi'
